version: '3.7'

services:
  origin:
    build:
      context: .
    image: manufacturedba/ovenmediaengine:latest
    ports:
      - "1935:1935/tcp"
      - "3334:3334/tcp"
      - "3479:3479/tcp"
      - "3478:3478/tcp"
      - "10000-10005:10000-10005/udp"
    environment:
      - OME_DISTRIBUTION=example.com
      - OME_DOMAIN_NAME=example.com
      - DEFAULT_ORIGIN_SERVER=192.168.0.160
      - OME_SIGNALLING_PORT=3334
      - OME_TCP_RELAY_ADDRESS=*:3479
      - OME_ICE_CANDIDATES=*:10000-10005/udp
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c origin_conf

  edge:
    build:
      context: .
    image: manufacturedba/ovenmediaengine:latest
    ports:
      - "1935:1935/tcp"
      - "3334:3334/tcp"
      - "3479:3479/tcp"
      - "3478:3478/tcp"
      - "10000-10005:10000-10005/udp"
    environment:
      - OME_DISTRIBUTION=example.com
      - OME_DOMAIN_NAME=example.com
      - DEFAULT_ORIGIN_SERVER=192.168.0.160
      - OME_SIGNALLING_PORT=3334
      - OME_TCP_RELAY_ADDRESS=*:3479
      - OME_ICE_CANDIDATES=*:10000-10005/udp
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c edge_conf
